# Generated by Django 5.0.4 on 2024-04-16 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='medico/'),
        ),
    ]
